# Generated by Django 3.1.3 on 2020-12-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myvoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_voucher', models.CharField(max_length=20)),
                ('kota', models.CharField(max_length=20)),
                ('diskon', models.CharField(max_length=6)),
                ('nama_merch', models.CharField(max_length=30)),
                ('nama_menu', models.CharField(max_length=20)),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField()),
                ('alamat', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=256)),
                ('gambar', models.BinaryField(blank=True)),
            ],
        ),
    ]
